# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Cornell Grant APP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cornell Grant APP
	pod 'Hero'
	pod 'Alamofire'
	pod 'SnapKit'

end
